<?php


/**
 * Implements hook_schema().
 *
 */
function moosend_schema() {
  $schema['cache_moosend'] = drupal_get_schema_unprocessed('system', 'cache');
  $schema['cache_moosend']['description'] = 'Cache table for the Moosend module to store a list of subsribers';
  return $schema;
}


/**
 * Implements hook_uninstall().
 *
 */
function moosend_uninstall() {
  variable_del('moosend_api_key');
}
