<?php


/**
 * Implements hook_menu().
 *
 */
function moosend_lists_menu() {

  $items = array();

   $items['admin/config/services/moosend/lists'] = array(
    'title' => 'Mailing Lists',
    'description' => 'Display Moosend Lists',
    'page callback' => 'moosend_lists_admin_page',
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend'),
    'file' => 'includes/moosend_lists.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/services/moosend/lists/add'] = array(
    'title' => 'Add a Mailing List',
    'description' => 'Add a new Moosend Mailing List.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('moosend_lists_add_lists_form'),
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend'),
    'file' => 'includes/moosend_lists.admin.inc',
    'type' => MENU_LOCAL_ACTION,
    'weight' => 5
  );

  $items['admin/config/services/moosend/lists/segment'] = array(
    'title' => 'Add Segments',
    'description' => 'Add a new Segment to Mailing List.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('moosend_lists_add_list_segments'),
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend'),
    'file' => 'includes/moosend_lists.admin.inc',
    'type' => MENU_LOCAL_ACTION,
    'weight' => 6
  );

  $items['admin/config/services/moosend/lists/clear_cache'] = array(
    'title' => 'Moosend lists clear cache',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('moosend_lists_cache_clear'),
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend'),
    'file' => 'includes/moosend_lists.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/services/moosend/lists/delete/%'] = array(
    'title' => 'Moosend delete List',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('moosend_lists_delete',6),
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend'),
    'file' => 'includes/moosend_lists.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}



/**
 * Access callback for mailchimp submodule menu items.
 */
function moosend_api_is_ready($permission) {
  if (initialize_moosend_api() && user_access($permission)) {
    return TRUE;
  }
  return FALSE;
}


/**
 * Implements hook_date_popup_process_alter().
 *
 */
function moosend_lists_date_popup_process_alter(&$element, $form_state, $context){
  if($context['form']['#form_id'] === 'moosend_lists_add_list_segments'){
    $element['#theme_wrappers'] = array('form_element');
    unset($element['date']['#title']);
  }
}
