<?php

/**
* @file
*  Moosend Campaigns Module.
*
*/

define('CAMPAIGN_DRAFT', 0);
define('CAMPAIGN_READY_TO_SEND', 1);
define('CAMPAIGN_SEND', 3);
define('CAMPAIGN_SMTP_READY_TO_SEND', 5);
define('CAMPAIGN_NOT_ENOUGH_CREDITS', 4);
define('CAMPAIGN_SENDING', 6);
define('CAMPAIGN_SELECTING_WINNER',11);
define('CAMPAIGN_ARCHIVED', 12);


/**
 * Implements hook_menu().
 *
 */
function moosend_campaigns_menu() {
  $items = array();

   $items['admin/config/services/moosend/campaigns'] = array(
    'title' => t('Campaigns'),
    'description' => 'Display Moosend Campaigns',
    'page callback' => 'moosend_campaigns_admin_page',
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend campaigns'),
    'file' => 'includes/moosend_campaigns.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/services/moosend/campaigns/add'] = array(
    'title' => t('Add a draft Campaign'),
    'description' => 'Add a Draft Moosend Campaign.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('moosend_campaigns_add_form'),
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend campaigns'),
    'file' => 'includes/moosend_campaigns.admin.inc',
    'type' => MENU_LOCAL_ACTION,
    'weight' => 5
  );

  $items['admin/config/services/moosend/campaigns/sent'] = array(
    'title' => t('Sent a Campaign'),
    'description' => 'Sent a Moosend Campaign.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('moosend_campaigns_sent_form'),
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend campaigns'),
    'file' => 'includes/moosend_campaigns.admin.inc',
    'type' => MENU_LOCAL_ACTION,
    'weight' => 6
  );

  $items['admin/config/services/moosend/campaigns/clear_cache'] = array(
    'title' => 'Moosend Campaigns clear cache',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('moosend_campaigns_clear_cache'),
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend campaigns'),
    'file' => 'includes/moosend_campaigns.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/services/moosend/campaigns/delete/%'] = array(
    'title' => 'Moosend delete List',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('moosend_campaigns_delete',6),
    'access callback' => 'moosend_api_is_ready',
    'access arguments' => array('administer moosend campaigns'),
    'file' => 'includes/moosend_campaigns.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 *
 */
function moosend_campaigns_permission() {
  return array(
    'administer moosend campaigns' => array(
      'title' => t('Administer Moosend Campaigns'),
      'description' => t('Administer Moosend settings for Campaigns'),
    ),
  );
}
